### ISSUE TITLE
 Does the 2.1 OC version of this SDK still work?

### ISSUE THREAD

**Issue by Jshto** [Shopify/mobile-buy-sdk-ios#1017]
Does the 2.1 or 2.2 OC version of this SDK work? I integrated it and reported 404 errors. In addition, many classes and methods in this swift version can not be referenced in OC. After changing some classes to inherit nsobject, some methods can not be referenced in OC. Unlike other swift third-party libraries, cocopods can be directly referenced in OC after import, and I would like to help OC use the SDK version or header file.

**Comment by dbart01** [comment]
This new version (3.x) of the SDK fundamentally does not support Objective-C interoperability. It relies on a GraphQL generator, and GraphQL DSL that isn't compatible with Objective-C. Even it were feasible to bridge the two languages, the developer UX would be very poor and cumbersome. There's really no need for it either. You can write a network layer (using the Swift SDK) that executes the required GraphQL queries and mutations that _is_ compatible with Objective-C and use _that_ in your app instead of requiring full Objective-C compatibility from the entire SDK.
