### ISSUE TITLE
Get which coupon code applied in checkout 

### ISSUE THREAD

**Issue by Komal2905** [Shopify/mobile-buy-sdk-ios#1043]
I have applied coupon code in checkout which is "MoneyV2" based, and it is successfully applied I can see that in checkout detail.
but what I could not find is that how to fetch which coupon has applied. 

<
{node(id:"NODE_ID"){__typename,... on Checkout{id,webUrl,currencyCode,subtotalPrice,totalPrice,discountApplications(first:1){edges{node{__typename,... on DiscountCodeApplication{applicable,code,value{__typename,... on MoneyV2{amount},... on PricingPercentageValue{percentage}}},... on ManualDiscountApplication{title},... on ScriptDiscountApplication{title}}}}}}}
>
I am using following query and can see coupon code in 

  discountApplications =     {
        edges =         (
                        {
                node =                 {
                    "__typename" = DiscountCodeApplication;
                    applicable = 1;
                    code = GET30;
                    value =                     {
                        "__typename" = MoneyV2;
                        amount = "48.0";
                    };
                };
            }
        );
    };

**Comment by rebeccajfriedman** [comment]
Hi @Komal2905 - it looks like the response you printed contains `code = GET30;`. This means that the coupon code was `GET30`. Hope this helps!

**Comment by Komal2905** [comment]
@rebeccajfriedman
though I am getting this response, I don't find any way to parse this.
like  discountApplications.edges.node.first.code - is this possible. or any way like this

**Comment by dbart01** [comment]
The trouble is that you're attempting to use `Storefront.DiscountApplication` directly. It is a GraphQL interface, which translates into Swift as a protocol. Since not all discount applications can be treated the same way, you must disambiguate the type before consuming it in your application layer. Please take a look at the sample app example for a [more in-depth example](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Sample%20Apps/Storefront/Storefront/DiscountApplication.swift#L35) on how to work with discount applications.
