### ISSUE TITLE
Include SDK via CocoaPods without the Passkit Framework?

### ISSUE THREAD

**Issue by dwnld-mitch** [Shopify/mobile-buy-sdk-ios#111]
Apologies if this isn't the correct way to ask this question, but is there any way to use the Mobile BUY SDK cocoapod without linking the Passkit framework?  Apple prevents app transfers for any apps built that include this framework, and I don't currently need any of the ApplePay integration.

**Comment by davidmuzi** [comment]
You'll need to modify the repo to remove the bits you don't need.  There is actually a branch for tvOS which strips out Passkit (since its not available on AppleTV) which you can see how its done

https://github.com/Shopify/mobile-buy-sdk-ios/blob/tvOS/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Data/BUYClient.m#L43

**Comment by dwnld-mitch** [comment]
Perfect, thanks!
