### ISSUE TITLE
Shipping and Billing Address ID not set on BuyAddress but is returned in the JSON

### ISSUE THREAD

**Issue by junketjim** [Shopify/mobile-buy-sdk-ios#147]
Upon updating a checkout for a known customer with addresses the shipping and billing addresses have a BUYObject ```identifier of nil```.  The BUYObject field for id is ```identifier``` but there is no mapping from ```id``` (in the JSON) to this field. 

Is this a bug or by design? If it's by design, how can we uniquely identify address objects for later use?

**Comment by biddster** [comment]
Looks to me like `[BUYAddress updateWithDictionary:]` is missing a call to `[super updateWithDictionary:dictionary];`.

Then `BUYObject.identifier` would be populated for the address. 

I've had a look at some of the other BUY objects. Seems to be a lack of consistency across them. 

E.g. `BUYLineItem` has its own field `lineItemIdentifier` rather than the super identifier.

**Comment by bgulanowski** [comment]
Thanks for pointing this out. We will look at it right away.

**Comment by dbart01** [comment]
Addressed in the 2.0 release. Closing.
