### ISSUE TITLE
JSON Caching Issue with  NSSet 

### ISSUE THREAD

**Issue by horsejockey** [Shopify/mobile-buy-sdk-ios#326]
I am having an issue caching the BUYProduct.  I am encoding the JSONDictionary object to Data and storing to disk then reading it back out again.  However, I think there is an issue writing the NSMutableSet properties like the BUYProductVariant options.  When I load these from the cache the property is nil.  NSOrderedMutableSet works fine.  This makes sense as arrays can be converted without any effort to JSON where Sets can't.  I am not an expert though so maybe I am missing something.

**Comment by bgulanowski** [comment]
The JSON encoder has not really been tested for models that are technically read-only (on the network). In other words, we only ever GET products and decode them as JSON. Although it's designed to handle ordered and unordered to-many relationships.

JSON transformation of many-to-many relationships rely on inferring ownership based on delete rules of the relationship. ProductVariant <-> OptionValue is a many-to-many relationship, so if there is a problem, it might be in many-to-many handling.

JSON encoding for a property happens in `NSPropertyDescription (BUYAdditions)` (and, specifically for this case, `-[NSRelationshipDescription buy_JSONForValue:]`).

- `-buy_JSONForValue:` conditionally encodes based on characteristics of the relationship. If it's a to-many property, it invokes
- `-buy_JSONForCollection:`, which uses
- `-buy_arrayForCollection:`, which checks whether the relationship is ordered.

Similar methods perform the decoding JSON -> objects.

Performing a test encoding of a product reveals that `BUYProductVariant.options` is not being encoded.

It turns out that `-[NSRelationshipDescription buy_JSONForValue:]` is not handling many-to-many relationships properly. It should check whether it owns the  the inverse relationship—`BUYOptionValue.variants`—allows inverse encoding, that is, `allowsInverseEncoding` is `YES`. 

The naming is a bit obscure, but we're essentially asking the relationship whether its associated entity can be encoded. In this case the answer is `YES`. But `-buy_JSONForValue:` was simply refusing to encode objects in a many-to-many relationship.

A Pull Request will be issued momentarily.

Thanks for reporting the issue.

**Comment by bgulanowski** [comment]
Actually, I am mistaken. many-to-many relationships cannot have ownership. Instead, the relationships should be encoded as IDs, so that they can be re-created during decoding. That will require a slightly different fix, this time to metadata on the relationship. I will be able to get to this later today or tomorrow.

**Comment by bgulanowski** [comment]
Hi. This turned out to be more subtle than it appeared at first. It may take a bit of time to get through review. I am going to PR it against develop first, and then, depending on internal review, we may be able to patch 2.0.1, but it may not make it before 2.1 (no release date set). You may be able to work off develop, or cherry pick what you need to your own fork in the meantime.

**Comment by horsejockey** [comment]
Any news on this issue?

**Comment by bgulanowski** [comment]
There is a PR already, but I wouldn't expect to see this in an official release for a while. Please feel free to look over my PR, and fork the repo if you need that fix. The JSON serialization is not designed for disk caching.

**Comment by antoinelamy** [comment]
@bgulanowski any alternative recommandation to perform disk caching? Online-only is simply not acceptable for some use cases.

**Comment by bgulanowski** [comment]
That would depend on the requirements of your application. On the simple end, look into `NSURLCache`. On the complex end, look into Core Data. Enhancing the JSON serialization support is worth exploring. But being able to create a serialized version of model objects is only part of the story. You would need to manage the cache for staleness and accuracy.

Caching is a pretty complex topic. Providing support for caching is outside the scope of the SDK.

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
