### ISSUE TITLE
App rejection due to conflicting non-public API "-didDismissViewController:"

### ISSUE THREAD

**Issue by dvrajan** [Shopify/mobile-buy-sdk-ios#350]
Hey Guys,

Our app recently got rejected due to the use of "-didDismissViewController:" API. We don't use the API in our code. But when searching for dependencies that might, we found that the Mobile-Buy-SDK uses it. 

Here is the response from Apple.

"Your app uses or references the following non-public APIs:

- didDismissViewController:

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

Please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions.

Additionally, if you are using third party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs."

**Comment by bgulanowski** [comment]
That's an accident of naming, unfortunately.

The method is not defined in the SDK framework itself (which, as of 2.0, has no view controllers), but in the sample app, in the `PaymentViewController`.

Unfortunately this is classic Apple: using obvious names on private methods that will eventually cause collisions.

I have added a standard-format bug report. You may wish to review it as an example of how to write a formal github issue.

**Comment by bgulanowski** [comment]
We use the API here, but only in the Advanced Sample application:

https://github.com/Shopify/mobile-buy-sdk-ios/blob/f4be3b7b0385d71e10a01b17003ef868022374cc/Mobile%20Buy%20SDK%20Sample%20Apps/Advanced%20App%20-%20ObjC/Mobile%20Buy%20SDK%20Advanced%20Sample/Product%20View/ProductViewController.m

If you are using SDK v1.x, you need to update to 2.x. If you are using 2.x, you should be OK. If you based your code on the sample app, you should change your code. You should not use the sample app code in a shipping application, because it was not designed for that.

**Comment by dvrajan** [comment]
Got it. Thanks!
