### ISSUE TITLE
BUYCollection.JSONDictionary() crashed with infinite recursion

### ISSUE THREAD

**Issue by sogko** [Shopify/mobile-buy-sdk-ios#351]
I need to return a BUYCollection as NSDictionary and figured I could use `BUYObject.JSONDictionary()` / `BUYObject.jsonDictionaryForCheckout()` to serialise it.

But it crashes when a BUYCollection has a BUYImage, which in turn, has a BUYCollection reference, which has a BUYImage, etc. (Cyclical reference)

Let me know if `JSONDictionary()` / `jsonDictionaryForCheckout()` are only meant to be used internally.

Steps to reproduce:

```objc

[_client getCollectionByHandle:handle completion:^(BUYCollection *collection, NSError *error){
      if (error == nil) {
        resolve([collection JSONDictionary]);
      } else {
        reject(@"ShopifyBuyClientGetCollectionByHandleFailed", @"Failed to get collection", error);
      }
    }];

```

Example response returned from API
```json
{
	"collection":  {
		"body_html": "",
		"collection_id": 157834887,
		"handle": "out-of-stock",
		"image": {
			"created_at": "2015-12-02T21:11:20-05:00",
			"src": "https://cdn.shopify.com/s/files/1/9999/9999/collections/7e6d379b-03b0-4ad6-8f49-05363af7196e.jpg?v=1449108680"
		},
		"published_at": "2016-05-21T10:40:00-04:00",
		"sort_order": "alpha-asa",
		"title": "Out Of Stock",
		"updated_at" : "2016-05-21T10:40:00-04:00"
	}
}
```

Cheers!

**Comment by bgulanowski** [comment]
The SDK includes JSON transformation support to enable network communication with Shopify. Since the storefront API (`-getCollections…`, `-getProducts…`) is read-only, we only ever *deserialize* collections or products in the SDK.

There is no reason that the SDK should not support converting inventory products back into JSON, but we have no immediate need for this, so we won't be providing a fix in the near future. If you need this, you are advised to investigate a solution yourself, and issue a pull request, which we can evaluate.

The fix for this may be simple, assuming it doesn't have side effects. If you are only using JSON, you are probably fine.

The relationship from `Collection.image` currently declares a delete rule of `Nullify`. Likewise the inverse relationship is also `Nullify`. This means that the SDK cannot infer ownership. Ownership is inferred when a delete rule is defined as `Cascade` (deleting an object also deletes its owned related objects.)

So you can try changing the delete rule on `Collection.image` to `Cascade` (but *NOT* on `ImageLink.collection`-- two objects cannot own each other). Then the method `-buy_allowsInverseEncoding:` defined in `BUYRelationshipDescription(BUYAdditiions)` will refuse to encode the `Collection` when encoding the `ImageLink`, thereby breaking the cycle.

You may note that the `Product.images` relationship already uses `Cascade` as the delete rule.
