### ISSUE TITLE
Nil Checkout During `provider:didCompleteCheckout:withStatus:` Callback

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#355]
It appears that during a web checkout using `BUYWebCheckoutPaymentProvider`, inside of the `provider:didCompleteCheckout:withStatus:`, the provided `BUYCheckout` is nil.

We use this provided checkout for displaying an order confirmation screen, with order number, etc.

**Comment by bgulanowski** [comment]
That's probably because the checkout is set to `nil` at the end of `-didReceiveCallbackURLNotification:` (line 213 or thereabouts), whereas it should happen inside the completion block provided to `-getCompletionStatusOfCheckoutURL:completion:`, invoked within.

Try moving line 213 to after line 205. I'll add this to `release/2.0.1`. Thanks for the report.

**Comment by EishanVijay** [comment]
Resolved in PR #361
