### ISSUE TITLE
Similar to issue #355, checkout.order is nil

### ISSUE THREAD

**Issue by samphomsopha** [Shopify/mobile-buy-sdk-ios#362]
Using BUYWebCheckoutPaymentProvider, after the order has been completed, "BUYPaymentProviderDidCompleteCheckoutNotificationKey" notification is not triggered. 

In addition, after checking that checkout.status == BUYStatus.complete, checkout.order is nil.  How do I get the order from checkout?

**Comment by bgulanowski** [comment]
The `BUYPaymentProviderDidCompleteCheckoutNotificationKey` is sent in the callback to a checkout status check in `-didReceiveCallbackURLNotification:`. That method is triggered when the web payment provider is notified of a `BUYSafariCallbackURLNotification`.

Your app should post the `BUYSafariCallbackURLNotification` when it dismisses the web view controller, or in response to the app resuming.

Whether there is an order attached to a checkout depends on when the checkout was retrieved. The SDK cannot, unfortunately, automatically update existing checkout objects. After a checkout completes, the new copy of the checkout returned from the SDK should include the order. Double check that the JSON for the retrieved checkout has the order content. But any other copies of the checkout you had from before checkout started will not have the order attached.

**Comment by samphomsopha** [comment]
Ok, I see. I'll give that a try.  Another question for BUYApplePayPaymentProvider, my delegate for didCompleteCheckout does get called, however buycheckout that is pass to it, checkout.order is also nil, is this expected?

**Comment by bgulanowski** [comment]
I think that's a real bug.

The payment provider implicitly waits for the completion status, and it retrieves the updated checkout from the server. However, this work is actually done by another object attached to the payment provider, called the `BUYApplePayAuthorizationDelegate`. This object _also_ has a `checkout` property, which gets updated, but the payment provider doesn't update its reference to the new checkout, so it's out-of-date when your delegate gets called.

I think the fix would be to add `self.checkout = self.applePayAuthorizationDelegate.checkout;` on line 245 of `BUYApplePayPaymentProvider.m` (in the completion block inside `-paymentAuthorizationViewController:didAuthorizePayment:completion:`), or on line 253 of `-paymentAuthorizationViewControllerDidFinish:`. 

As a workaround, you could get the new checkout using key-value coding. In your delegate's implementation of `-paymentProvider:didCompleteCheckout:withStatus:`, try this:

`self.checkout = [paymentProvider valueForKeyPath:@"applePayAuthorizationDelegate.checkout];`

This is dirty, since you're not supposed to know about the private property `applePayAuthorizationDelegate`, but this should work until we get a fix in.

**Comment by bgulanowski** [comment]
A less dirty solution would be to download the checkout again, at the cost of more latency on an already slow process.

**Comment by samphomsopha** [comment]
Ok great, thanks for the quick response.  I was able to do a work around with the information you provided.
