### ISSUE TITLE
Adding variants with same identifier not changing quantity

### ISSUE THREAD

**Issue by ajinian** [Shopify/mobile-buy-sdk-ios#372]
Hi guys, 

Looks like adding multiple variants with same id are treated as unique line items, instead of increasing the quantity. 

Could you please look into it, debug screenshot of BUYCart object is attached.

I am using Mobile-Buy-SDK 2.0.1

Thanks! 

![screen shot 2016-10-20 at 7 53 55 am](https://cloud.githubusercontent.com/assets/1855532/19565399/90364368-969b-11e6-9a21-449e20be131b.png)

**Comment by bgulanowski** [comment]
How are you adding the line item?

For all bug reports, please provide exact steps to reproduce.

**Comment by ajinian** [comment]
I am adding BUYProductVariant object to BUYCart object using [BUYCart:addVariant:variant] method. 
[self.cart addVariant:productVariant]; where productVariant is instance of BUYProductVariant.

**Comment by ajinian** [comment]
Yes, code is very similar to what I got. 

See attached debug screenshot for [BUYCart:addVariant:] method.

I've placed a break point in the method as soon as I am adding second variant that has same identifier as previously added variant.

As you can see in debug screen, self.lineItems already includes a variant that was added previously.

However, notice that [self lineItemForVariant:variant] method returned nil for some reason. 

This is effectively adding new variant as a unique lineItem, instead of increasing quantity of existing variant.

![screen shot 2016-10-21 at 1 02 16 pm](https://cloud.githubusercontent.com/assets/1855532/19610226/233c180a-9790-11e6-980b-d6e9aa2917e1.png)

**Comment by ajinian** [comment]
Hi guys, 

Have you been able to reproduce this? 

Thanks,

**Comment by davidmuzi** [comment]
No we have not.  To allow us to reproduce this, please supply sample code or project that demonstrates the issue.

Also, does the issue occur with the sample code I provided?

**Comment by bgulanowski** [comment]
When you say "lineItemForVariant: returned nil *for some reason*", the thing to do is to determine exactly what that reason is. Please let us know.

**Comment by ajinian** [comment]
I was able to trace it all the way to [BUYCart:linetItemForVariant:varian] method in your SDK. 

This method fails finding existing variant. 

Please see attached debugger screenshot, with breakpoint at line 117 in BUYCart.m:
![screen shot 2016-11-11 at 3 13 28 pm](https://cloud.githubusercontent.com/assets/1855532/20233038/773b2396-a821-11e6-9da2-39df2f58a3f0.png)

**Comment by bgulanowski** [comment]
The code does not correctly work when the two variants are different objects, because we didn't implement a custom `isEqualTo:` for model objects. There was an implicit assumption that the same object would be used to represent the same variant. Thanks for reporting the issue. We should be able to get a fix into 2.1. For now, you can change the predicate to compare the identifiers instead of variants themselves.

**Comment by JohnStratoudakis** [comment]
I am encountering the same issue.  Am trying to figure out how to change the predicate, if anybody knows exactly how to do this please do say!

**Comment by JohnStratoudakis** [comment]
Okay, I figured it out:

I modified the file BUYCart.m in 2 places:
* I added an extra header include because BUYProductVariant had a forward declaration:
#import "BUYProductVariant.h"
* I changed the method **linetItemForVariant** to compare identifiers

`- (BUYCartLineItem *)linetItemForVariant:(BUYProductVariant *)variant`
`{`
 `   return [[self.lineItems filteredOrderedSetUsingPredicate:[NSPredicate predicateWithFormat:@"variantId = %@", [variant identifier]]] lastObject];`
`//	return [[self.lineItems filteredOrderedSetUsingPredicate:[NSPredicate predicateWithFormat:@"variant = %@", variant]] lastObject];`
`}`
