### ISSUE TITLE
iOS: Cart subtotal (better documentation?)

### ISSUE THREAD

**Issue by mihaibulic** [Shopify/mobile-buy-sdk-ios#389]
I'd like to show the current cart's subtotal at the top of my app.  I'd like to do it offline since it should update instantly when users add/remove things to/from their cart.

Also, is there documentation on any of this stuff?  I'm constantly feeling around in the dark w/ the iOS BUY sdk :(
```

        let cart = client.modelManager.insertCart(withJSONDictionary: nil)
        cart.setVariant(variant, withTotalQuantity: quantity)
        let checkout = client.modelManager.checkout(with: cart)
        print(checkout.subtotalPrice) // this is nil :O

        client.createCheckout(checkout) { (checkout, error) in
            print(checkout?.subtotalPrice) // this is not nil but it's slowww
        }
```

**Comment by davidmuzi** [comment]
Hi @mihaibulic,

You can find our API docs here: http://cocoadocs.org/docsets/Mobile-Buy-SDK/2.0.1/Classes/BUYCartLineItem.html

To calculate the cart subtotal offline, you can sum the `linePrice` on each `BUYCartLineItem` in the cart.

Keep in mind, that the cart totals may not be as accurate as a checkout since taxes will be missing, as well as potential cart scripts that could be executed.

Can you detail the items that are leaving you in the dark with the SDK?

**Comment by mihaibulic** [comment]
Ok cool, yeah that's what I just switched to, thanks.

the link to the api docs is all I need, thanks!

**Comment by davidmuzi** [comment]
To think of it, you may want to create categories on BUYCart to easily get the cart total.  Remember, PRs are welcome :)
