### ISSUE TITLE
Line Item Properties?

### ISSUE THREAD

**Issue by germania** [Shopify/mobile-buy-sdk-ios#423]
Hi,

I'm looking through the source for BuyCartLineItem.m ( https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/Persistent/BUYCartLineItem.m ) and on a few minutes of reading, it appears that this SDK doesn't support line item properties, which the storefront we're building an app for relies on pretty heavily.  Can somebody confirm this is the case, and perhaps direct me on a workaround or what would be necessary to add this to the SDK?

Thanks!

**Comment by davidmuzi** [comment]
Is this what you are looking for? 
https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/Persistent/_BUYLineItem.h#L124

**Comment by germania** [comment]
It appears to be what I'm looking for, thank you!

**Comment by germania** [comment]
Sorry to be a pain on this, that does indeed look like what I need, however I can't seem to find a way to use it.  When I'm adding a product variant to the cart, it gets added as a BuyCartLineItem.  What you've linked is a _BuyLineItem.  Forgive me if I can't see the forest for the trees, but is there some example code for this somewhere, or some direction on using _BuyLineItem instead of BuyCartLineItem?

Thanks again

**Comment by davidmuzi** [comment]
This appears to be a bug.  You should be able to set the properties on a lineitem from the checkout object, and call update on it

**Comment by bgulanowski** [comment]
The generation of the JSON that is performed in the `JSONDictionary` getter (implemented in the extensions to `NSEntityDescription` and `NSPropertyDescription`) should include the line item properties.

I speculate that changing the `properties` attribute of a `BUYLineItem` does not get treated as a modification of the checkout object itself, so the dirty state of the checkout does not include its `lineitems` property.

As a workaround, try to reset the line items on the checkout after changing them. This will notify the change tracker that the line items are different.

A similar problem would undoubtedly happen for properties of any related objects of a checkout. But most of those objects do not themselves allow fine-grained editing. Even in the line item case, only the `properties` property is editable.

The solution may be to gate changes to these child objects through the checkout object itself. Alternately, the child objects could "magically" (or otherwise) inform the checkout that its properties are changing.

**Comment by germania** [comment]
Really appreciate the efforts on tracking this down, guys.  @bgulanowski, how can I test your workaround and reset the line items?

**Comment by bgulanowski** [comment]
I was hoping that it would be as simple as `checkout.lineItems = checkout.lineItems`.

**Comment by master83** [comment]
I have a question. If I add `LineItems` with my `checkout` then how would I link `lineitems` with particular `productVariant`? Suppose user adds multiple product variants to their cart and I want to let user add `properties` (could be color, size etc.) for all the variants they have added in the `cart` then how would I link `LineProperties` with those product variants?

**Comment by bgulanowski** [comment]
`size` and `color` are usually defined as `Option`s and `OptionValue`s, not as line item properties. But I'll assume you mean something different that requires line item properties.

It's not completely clear what you mean by "link". Strictly speaking, you can't link arbitrary data with a `ProductVariant`. The contents of line items are relevant to the order and fulfillment, which is going to be handled outside of Shopify, either by a person or by a custom app.

In future, please ask questions like this on the Shopify ecommerce forums. This is not a Q&A site. This is for issue tracking in development.

https://ecommerce.shopify.com/c/shopify-apis-and-technology

If you don't get a timely answer on the forums, link to it from here, and we'll close the issue here and answer the question on the forums. Thanks.
