### ISSUE TITLE
CartToken is always nil on BUYCheckout

### ISSUE THREAD

**Issue by pconno** [Shopify/mobile-buy-sdk-ios#484]
I am trying to use `BUYClient createCheckoutWithCartToken` but I am unable to get a cartToken to use. The use case is that I want to save off an abandoned cart to `NSUserDefaults` if the user has left the app without purchasing. It appears that the cartToken property on BUYCheckout is never populated. There is code in `BuyCheckout updateWithDictionary` that attempts to do this but the resulting jsonDictionary never contains a key/value for cart_token. Furthermore, by examining the Checkout API, it doesn't seem like the request should ever contain cart_token, https://help.shopify.com/api/reference/checkout#show. Are there any plans to add this property? Is there any other way to restore an abandoned cart in using the SDK?

**Comment by bgulanowski** [comment]
You do not need a cart token to create a checkout. A cart token comes from Shopify as a web cart that the SDK can convert into a checkout. It will typically come as a special cart link URL, from which the token needs to be extracted. The SDK cannot access carts from Shopify through the API.

Carts in the SDK are client-side only. You can convert a client-side cart into a checkout. When you create the checkout and push it up to Shopify, the new checkout returned will have a checkout token. You can save this, if you want.

Another approach is to serialize the cart contents, without creating a checkout. The SDK doesn't include support for cart serialization, but some other developers have done this.

I don't suggest trying to serialize the entire cart, actually. It is better to design a custom model that saves only the variant id and quantity. You will also need to save the product ids that own those variants, in order to be able to request them, since there is no way to retrieve variants directly from the API.

Something like
```JSON
{
"cart_contents" : {
  "line_items" : [
    {
        "variant_id" : 1,
        "quantity" : 1,
    },
    {
        "variant_id" : 8,
        "quantity" : 2,
    }
  ],
  "product_ids" : [ 10, 22, 91, 32 ]
}
}
```

**Comment by pconno** [comment]
Okay, understood and thanks for the quick response. How would I use the checkout token tho? BuyClient doesn't have a function to initialize a checkout with a checkout token.

It sounds like the route, that I should take is as you suggested, storing the line items and recreating the cart from those.

Thanks

**Comment by bgulanowski** [comment]
After creating and getting back the checkout with the token, you can save the token however you want. Then you can later request the checkout from Shopify, using the token. Shopify will return you the Truth about the checkout. Then you can make additional changes to it, and save them to Shopify. Always use the checkout returned to you when using checkout API on the `BUYClient`.

**Comment by pconno** [comment]
Right, but I don't believe there is a method on BuyClient that can be used that takes in a checkout token as a parameter to generate a previously begun checkout.

The methods are 

`- (NSURLSessionDataTask *)createCheckoutWithCartToken:(NSString *)cartToken completion:(BUYDataCheckoutBlock)block;`

`- (NSURLSessionDataTask *)createCheckout:(BUYCheckout *)checkout completion:(BUYDataCheckoutBlock)block;`

Additionally BUYCheckout doesn't have any methods to initialize from a checkout token, only the cart

`- (instancetype)initWithCartToken:(NSString *)cartToken`
`- (instancetype)initWithCart:(BUYCart *)cart`

Because there are no methods, I would have write code to hit the Shopify API directly. This could certainly be done if I forked the SDK. But operating outside of the SDK it seems it wouldn't be possible?

**Comment by bgulanowski** [comment]
I updated my previous comment. It seems like you missed one of the API methods for checkouts.

**Comment by pconno** [comment]
Oh man, you're right! I missed that one.

Thanks!
