### ISSUE TITLE
didCompleteCheckout is not called

### ISSUE THREAD

**Issue by unittesting0** [Shopify/mobile-buy-sdk-ios#486]
I'm using the webView and `paymentProviderDidDismissCheckout:` is called but the `didCompleteCheckout:` is not called.

    func paymentProvider(provider: BUYPaymentProvider, didCompleteCheckout checkout: BUYCheckout, withStatus status: BUYStatus){
        if status == .Complete {
            print("Checkout is completed")
            // Now the checkout is complete and you can discard it, and clean up
            self.checkout = nil
        } else {
            // status will be 'BUYStatusFailed'; handle error
            print("Checkout Failed")
        }
    }

How can I know when the user has purchased something or when it fails.

I have added this code in `viewDidLoad()`: 

```
webPaymentProvider = BUYWebCheckoutPaymentProvider(client: self.client)
webPaymentProvider!.delegate = self
```

and then
```
self.client.createCheckout(checkout, completion: {(checkout: BUYCheckout?, error: NSError?) in
                if error == nil {
                    self.checkout = checkout!
                    self.webPaymentProvider!.startCheckout(checkout!)
                 }
```

P.S also `didFailWithError:` is not called
What am I missing guys?

**Comment by davidmuzi** [comment]
Since the checkout is happening in a SafariViewController, you don't get access to the status of the checkout while its happening.  If you hold onto the checkout token, you can use it to [get the checkout status](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Data/BUYClient+Checkout.h#L155) when you return to the view that presented the web checkout (in case the customer backs out).  

To check for completion, you can set the `urlScheme` property on the `checkout` to a URLScheme your app can handle, the web checkout will present a button to the customer when the checkout completes, which will redirect to the method `application:openURL` in your AppDelegate [See the Advanced Sample App](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK%20Sample%20Apps/Advanced%20App%20-%20ObjC/Mobile%20Buy%20SDK%20Advanced%20Sample/AppDelegate.m#L45).  You can use that URL to get the status of the checkout by calling  [getCompletionStatusOfCheckoutURL](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Data/BUYClient+Checkout.h#L165)

**Comment by unittesting0** [comment]
Thank you davidmuzi, I'm checking if the user has completed or not through the `checkout.token`, may I know if this token expires or can give failed even if the user completes it?

Method II:
`            self.client.urlScheme = "shopifyCheckOutTest"`
            `self.checkout?.webReturnToURL = NSURL(string: "shopifyCheckOutTest://")`
            `self.checkout?.webReturnToLabel = "Return to ShopifyCheckOutTest"`

But after I make a purchase and click "Return to ShopifyCheckOutTest" it does not get back to the app :(

**Comment by davidmuzi** [comment]
Tokens dont expire, so you will always be able to get the status of a checkout.

For the second issue, ensure you've registered the URL Scheme to your app.  You should be able to enter `shopifyCheckOutTest://` in mobile Safari, and your app should open. See the Advanced sample app which has a working version of this
