### ISSUE TITLE
"Payfort - Start" Payment gateway not working with Credit card option

### ISSUE THREAD

**Issue by AkashDoshi19** [Shopify/mobile-buy-sdk-ios#490]
Hi ,
 We are developing iOS and Android app for shopfy store. We have integrated MobileBuy SDK. When we tried to do native checkout with credit card we are getting below error
```
Error Domain=BUYShopifyErrorDomain Code=422 "(null)" UserInfo={errors={
   "payment_gateway" =     (
               {
           code = invalid;
           message = "is invalid";
           options =             {
           };
       }
   );
}}
```
We have integrated “Payfort - Start” payment gateway which listed in Payment Gateways Supported document.

**Comment by davidmuzi** [comment]
Can you provide the payload and the URL which resulted in the 422

**Comment by AkashDoshi19** [comment]
*checkout url*
https://elb.deposit.shopifycs.com/sessions
*payload*
{
    checkout =     {
        "billing_address" =         {
            address1 = Dubai Investments Park Office United Arab Emirates;
            address2 = Office;
            city = Dubai;
            company = "";
            country = "United Arab Emirates";
            "country_code" = AE;
            "first_name" = Akash;
            id = 7696372999;
            "last_name" = D;
            phone = 9890113186;
            province = Dubai;
            "province_code" = DU;
        };
        "credit_card" =         {
            month = 6;
            name = "no mo";
            number = 5555555555554444;
            "verification_value" = 333;
            year = 2019;
        };
        token = c1a3d3acf0d6595bfc982be6a1fb4ce3;
    };
}

**Comment by louisvanier** [comment]
You can find the documentation for the checkout API here: https://help.shopify.com/api/reference/checkout

Here's a quick overview: In order to process payment you have to send the credit card parameters to the cardvaulting endpoint at https://elb.deposit.shopifycs.com/sessions
i.e.
```
"credit_card" = {
month = 6;
name = "no mo";
number = 5555555555554444;
"verification_value" = 333;
year = 2019;
};
```

this will give you back a session id, which you should then be able to POST with the amount on the payments endpoint of your checkout in order to pay.

```
{
  "payment": {
    "request_details": {
      "ip_address": "123.1.1.1",
      "accept_language": "en-US,en;q=0.8,fr;q=0.6",
      "user_agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.98 Safari\/537.36"
    },
    "amount": "408.99",
    "session_id": "global-9c7c786bc76b2816",
    "unique_token": "client-side-idempotency-token"
  }
}```

**Comment by Michael-James-Ross** [comment]
Where can i get "unique_token" or i have to generate "client-side-idempotency-token" ?

**Comment by dbart01** [comment]
You can generate one using `UUID().uuidString`. That would give you something like:
```swift
"5AB102C6-8DC3-40AA-AC32-B0744CC4DA36"
```

**Comment by louisvanier** [comment]
Yes exactly the `unique_token` here is to allow for idempotent operations. Essentially you generate a token for the payment attempt on the client-side, that way if anything happens before the operation completes and you receive the resource in response, you can always try to re-create the payment with the same token. You'll get back a brand new payment if creation failed server-side, or the payment created with the same token otherwise, i.e. it makes the operation idempotent.

**Comment by Michael-James-Ross** [comment]
Thanks guys, but i still have an error like this: 
I'm trying to make test payment with existing checkout
![image](https://cloud.githubusercontent.com/assets/12801769/26253075/bdab1ad8-3cba-11e7-9013-824a0e15da20.png)
![image](https://cloud.githubusercontent.com/assets/12801769/26253171/12560c78-3cbb-11e7-9ba5-9d179c691ec0.png)

**Comment by louisvanier** [comment]
It looks like you're not properly authenticated in Postman, where does the access token you're using come from?

**Comment by Michael-James-Ross** [comment]
If you mean X-Access-Shopify-Token, it's in headers of my requests.  Without X-Access-Shopify-Token I'm not able to see even these results

**Comment by louisvanier** [comment]
Yes the access token is sent via the header `X-Access-Shopify-Token`, but where does the value sent in the header comes from in the case where you hit a 404? It looks like you're authenticated as an api client that is not authorized to process payments.

**Comment by Michael-James-Ross** [comment]
Which value ?
I've received sessionId from anouther request. You mean sessionId or some specific vault token ?

**Comment by louisvanier** [comment]
It seems like you have `sessionId` which comes from the card vault and is about payments confused with `X-Shopify-Access-Token` which is the access token to authentify you against Shopify's platform. I'm talking about the latter.

**Comment by Michael-James-Ross** [comment]
Sorry if I'm totally tired you and thank you for helping me
For authentication in card vault I also need X-Shopify-Access-Token. session ID  - for getting money from customer.

**Comment by louisvanier** [comment]
I think were missing common vocabulary here. I'll refer to my previous comment https://github.com/Shopify/mobile-buy-sdk-ios/issues/490#issuecomment-276967796 with the links to the API documentation, there you should find some example of the flow to create a checkout, get a session ID form the card vault where you post credit card information, and then `POST` that session ID to shopify to process the payment for the checkout you are processing. 

What I'm asking is the access token you use to authentify against Shopify, not the card vault. It seems like you are not authed as an API client with the rights to process payments hence you hit a 404 when you `POST` the session ID from the card vault to Shopify.

**Comment by Michael-James-Ross** [comment]
I've understood you.
Look: I've made a sales channel public app and while installing this app in my shop I've got access token.
Using this token I make requests to checkout API because without it I'm not able to do that (it throws error "User must have sales channel abilities" - that's why I've made sales channel). I installed sales channel, followed these steps, I've got that session Id (https://help.shopify.com/api/tutorials/sell-through-the-checkout-api#card-vaulting), and using this sessionId, generated UUID for unique_token and  X-Shopify-Access-Token in headers I've got that error. I didn't сonfuse X-Shopify-Access-Token with sessionId. I just hid that token on the image and I already have write checkouts scope (payments scope I didn't find).
Maybe I need to have shopify plus account ? Or it's impossible to do that ? (Because I just want to do my own checkout page and on the shopify's forums I found out that it's almost impossible)

**Comment by jamiemtdwyer** [comment]
It sounds like there may be a few different issues here:

* Payfort is not a direct gateway on Shopify. Checkouts can only be created against _direct_ payment gateways.

As for Michael's issue, not all applications are granted access to process payments on Shopify, as this is a sensitive action. 

You'll need to request access to process payments from your partner dashboard:

![image](https://cloud.githubusercontent.com/assets/16005948/26692089/7576a526-46cd-11e7-918f-0327b9bf6537.png)

Not all applications will be accepted to process payments. You will be vetted by your use-case – right now, this feature is intended to be used for marketplaces and other aggregation platforms.

Hope this helps.

**Comment by Michael-James-Ross** [comment]
Thanks, jamiemtdwyer 
I thought that I would get error with more description. I used to think that I do invalid requests to API
