### ISSUE TITLE
 getProducts and getCollections, parsing product, collection error, NSArrayM insertObject:atIndex:]: object cannot be nil'

### ISSUE THREAD

**Issue by webmaster100** [Shopify/mobile-buy-sdk-ios#561]
Hi, I want to use the mobile-buy-sdk-ios with react-native-shopify. When calling methods getProducts(1) and getCollections(1) the products and collections are returned from the requests, but some parsing error occurs after that. The error seems to occur after this line: 
![nsarray buyadditions m edited 2017-04-03 18-25-41](https://cloud.githubusercontent.com/assets/10449011/24622754/c4a9c710-18ae-11e7-874c-a0e5a7e2d754.png)
![error_nil_object](https://cloud.githubusercontent.com/assets/10449011/24622895/4ab6be58-18af-11e7-8714-fa613edb456c.png)
Can you advise what causes this error and how can I resolve it?
Thank you!

**Comment by bgulanowski** [comment]
This usually happens because your app was unable to create the managed object model. Probably because it couldn't find the managed object model file, `Mobile Buy SDK.xcdatamodeld`, in the bundle. Possibly because you didn't include the SDK resources bundle in your target.

In the code you show there, the problem is that `block(obj)` is returning `nil`. If you step into that block (defined in `+[BUYModelManager buy_objectsWithEntityName:JSONArray:]`, you'd see that the `cls` variable is probably `nil`, so object instantiation fails. `cls` is nil because the model manager's `model` property is `nil`. Basically, you have a cascade of `nil` values.

You will have to trace it back to be sure, however.

**Comment by webmaster100** [comment]
I have installed the mobile-buy-sdk-ios using Cocoapods and as I see it automatically connects the resources. It is the only place where I found it in the workspace in Xcode
![image](https://cloud.githubusercontent.com/assets/10449011/24644398/02e3cd1a-191c-11e7-9f80-ee2d9a428f43.png)
The cls variable have the value:
![buymodelmanager m edited 2017-04-04 10-07-46](https://cloud.githubusercontent.com/assets/10449011/24644977/f725a6b2-191e-11e7-9da1-762e33e4cbe2.png)
Can be there some product parsing error?

**Comment by bgulanowski** [comment]
Your screenshot clearly shows `cls` == `0x0`, in other words, `Nil` (I incorrectly said `nil` before). `cls` should be a class object. Without that, `[cls alloc]` is `nil`. So there's no reason that I can see to suspect a parsing error.

If there was a parsing error, it would be in Apple's JSON deserialization, but in that case, you would have seen an error logged to the console and `nil` returned instead of a dictionary. You should be able to easily verify that. In terms of mapping the dictionary contents to a new object, even if that failed for some reason, you would still get a new object returned, but it's properties would not have the right values.

**Comment by webmaster100** [comment]
The error was fixed when I copied by reference the datamodel file to Compile Sources as mentioned in this  [thread](https://github.com/Shopify/mobile-buy-sdk-ios/issues/405)
![image](https://cloud.githubusercontent.com/assets/10449011/24697453/e4f9077c-19f5-11e7-8739-a964e737a2e1.png)
Thank you!

**Comment by JaydeepPatel** [comment]
@webmaster100  Hello Sir, You have idea in WebCheckout and Shipping rates ?

**Comment by webmaster100** [comment]
@JaydeepPatel, 
Hello, I used react-native-shopify package for webcheckout and getting shipping rates.
