### ISSUE TITLE
Apple  pay is not working in  2.2.0 Version with iOS 10

### ISSUE THREAD

**Issue by muneerkk66** [Shopify/mobile-buy-sdk-ios#639]
Hi Team,

  When i tried with 2.2.0 version on iOS 10 apple  pay delegate is not calling but it's working on iOS 9.           Please see the details below.
 These are the delegates which i used in 2.2.0 version
 BUYPaymentProviderDelegate
 PKPaymentAuthorizationViewControllerDelegate

After that i updated the delegate method using PKPaymentAuthorizationControllerDelegate, but in iOS 10 it's working and not in iOS 9

Please help me to resolve this issue

**Comment by muneerkk66** [comment]
@dbart01  You mean it's a existing bug ?

**Comment by dbart01** [comment]
We can't confirm the issue without additional information. What is the method that you're expecting to be called? Which one is being called instead? Please provide clear steps to reproduce the problem.

**Comment by muneerkk66** [comment]
I am using PKPaymentAuthorizationControllerDelegate now. 

 - (void)paymentAuthorizationController:(PKPaymentAuthorizationController *)controller
			   didSelectShippingMethod:(PKShippingMethod *)shippingMethod
							completion:(BUYShippingMethodCompletion)completion

This method is suppose to call when the shipping address is selected. But this is not getting called in iOS 9. So it is failed to retrieve the shipping rate. Thus the payment is become a failure.

**Comment by dbart01** [comment]
`PKPaymentAuthorizationController` is only available on iOS 10.0 and higher.

**Comment by muneerkk66** [comment]
So 2.2.0 version is indent to support iOS 10 only. If NO what are the changes i need to make to support iOS 9.

  What about the latest version 3.0 ?

**Comment by dbart01** [comment]
Version 2.2.0 does support iOS 9 but the delegate method you referenced is only available on iOS 10. It will never be called running on iOS 9 and lower. 

We encourage migrating to the latest `3.0` release, however, the `Pay` target only support iOS 10.0. Something to keep in mind when considering a migration to `3.0`.

**Comment by muneerkk66** [comment]
I have also define PKPaymentAuthorizationViewControllerDelegate in my class to support iOS9 
func paymentAuthorizationViewController(_ controller: PKPaymentAuthorizationViewController, didSelectShippingContact contact: PKContact, completion: @escaping (PKPaymentAuthorizationStatus, [PKShippingMethod], [PKPaymentSummaryItem]) -> Swift.Void)
But The control didn't reach here.
 
Anything i missed here or Do you have any new alternate method for supporting iOS 9 in Version 2.2.0

**Comment by dbart01** [comment]
If you're using the `PKPaymentAuthorizationViewControllerDelegate`, you have to also use the corresponding `PKPaymentAuthorizationViewController` and **NOT** the `PKPaymentAuthorizationController`.

For a complete guide on Apple Pay, please see the [Apple's programming guide](https://developer.apple.com/library/content/ApplePay_Guide/Authorization.html#//apple_ref/doc/uid/TP40014764-CH4-SW3).

**Comment by davidmuzi** [comment]
@muneerkk66 If you are using the `BUYPaymentController`, the `BUYApplePayPaymentProvider` will instantiate the correct Apple Pay Controller according to the device its running on.

On iOS 9 the PKPaymentAuthorization**View**Controller and its delegate is used instead. 
https://github.com/Shopify/mobile-buy-sdk-ios/blob/2.2.0/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Payment%20Providers/BUYApplePayPaymentProvider.m#L78

So instead of 
`- (void)paymentAuthorizationController:(PKPaymentAuthorizationController *)controller
			  didSelectShippingContact:(PKContact *)contact
							completion:(BUYAddressUpdateCompletion)completion`

It will call `-(void)paymentAuthorizationViewController:(PKPaymentAuthorizationViewController *)controller
				 didSelectShippingContact:(PKContact *)contact
							   completion:(BUYAddressUpdateCompletion)completion` 

Both methods call into the common method: 
`https://github.com/Shopify/mobile-buy-sdk-ios/blob/2.2.0/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Utils/BUYApplePayAuthorizationDelegate.m#L203`

which would be a good place to put a breakpoint.

If you are not using the `BUYPaymentController`, you will have to consult the Apple Pay programming guide as @dbart01 suggested.

**Comment by muneerkk66** [comment]
@dbart01 

I have defined this for iOS 10.

func paymentProvider(_ provider: BUYPaymentProvider, wantsPaymentControllerPresented controller: PKPaymentAuthorizationController) {
        let applePayController : PKPaymentAuthorizationController = controller
        applePayController.delegate = self
        MBProgressHUD.hideAllHUDs(for:view, animated: true)
        applePayController.present(completion: nil)
    }

Also defined this for iOS 9.
    func paymentProvider(_ provider: BUYPaymentProvider, wantsControllerPresented controller: UIViewController){
        
        let applePayController : PKPaymentAuthorizationViewController = controller as! PKPaymentAuthorizationViewController
        applePayController.delegate = (self as! PKPaymentAuthorizationViewControllerDelegate)
        MBProgressHUD.hideAllHUDs(for:view, animated: true)
        present(applePayController, animated: true, completion: nil)
    }

Then it should have invoked corresponding delegates which is not happening in the case of iOS 9.

What I have observerd is , for iOS 9 also the controller reached in this method
func paymentProvider(_ provider: BUYPaymentProvider, wantsPaymentControllerPresented controller: PKPaymentAuthorizationController)

instead of  PKPaymentAuthorizationViewController.

**Comment by dbart01** [comment]
`PKPaymentAuthorizationViewController` != `PKPaymentAuthorizationController`. You can't just cast between the two. One is a `UIViewController`, the other is an `NSObject`.

It doesn't look like you're using Apple Pay helpers provided in the SDK. As a result, any issues you're running into are the result of incorrect implementation of Apple Pay classes, which unrelated to this SDK. If you wish to use SDK features to support Apple Pay, you can refer to our sample application for a [working implementation of Apple Pay](https://github.com/Shopify/mobile-buy-sdk-ios/blob/2.2.0/Mobile%20Buy%20SDK%20Sample%20Apps/Advanced%20App%20-%20ObjC/Mobile%20Buy%20SDK%20Advanced%20Sample/CheckoutViewController.m#L234).

Otherwise, please read [Apple's Apple Pay integration guide](https://developer.apple.com/library/content/ApplePay_Guide/Authorization.html#//apple_ref/doc/uid/TP40014764-CH4-SW3).

**Comment by SharadExt** [comment]
Hi Team, I have NSObject class in that i need to show apple pay so I am using PKPaymentAuthorizationController instead of PKPaymentAuthorizationViewController.
Apple pay sheet is displayed but delegate method does not called >
Here is my code
