### ISSUE TITLE
How do you login customers using version 3.0.1 of the sdk?

### ISSUE THREAD

**Issue by Meeks91** [Shopify/mobile-buy-sdk-ios#650]
You used to be able to login customers with the client.loginCustomer(with: loginCredentials)  method but how do you login customers using the new sdk?

Thanks in advance.

**Comment by dbart01** [comment]
The process of customer login is actually a type of mutation since it creates an access token on the server. All mutations are built using `Storefront.buildMutation()`. You can create a login mutation like this:

```swift
let input    = Storefront.CustomerAccessTokenCreateInput(email: "", password: "")
let mutation = Storefront.buildMutation { $0
    .customerAccessTokenCreate(input: input) { $0
        .customerAccessToken { $0
            .accessToken()
            .expiresAt()
        }

        // Don't forget to check for user errors!!
        .userErrors { $0
            .field()
            .message()
        }
    }
}

let task = client.mutateGraphWith(mutation) { result, error in
    // Handle result and errors here
}

task.resume()
```

__Please keep in mind that GitHub issues are reserved for *problems* or *issues* with the SDK. General help questions should be posted on [our forum](https://ecommerce.shopify.com/c/shopify-apis-and-technology).__

**Comment by Meeks91** [comment]
Sorry for the delayed reply. 

Thanks for your help with this. 

Cheers

**Comment by Meeks91** [comment]
Hi, 

I did try this code however I get `Buy.Graph.QueryError.http(403)` when I execute it. However, if I try and login using the same customer credentials on the Shopify website then I can successfully login.

Do you know what could be causing this error? 

I did change the hardcoded`""` username and password that you used in the example. I also asked in the forum for help with registering users but got no response so I'm asking this question here instead of there.

Thanks in advance.
