### ISSUE TITLE
Incorrect api behavior

### ISSUE THREAD

**Issue by powerscin** [Shopify/mobile-buy-sdk-ios#665]
Swift, iOS, SDK version 2.2.0

I use property `publishedAtDate` in `BUYProduct` object. And in your code it is marked as NonNull and for some users it crashes.
```
libswiftFoundation.dylib       0x10148c3d0 static
Date._unconditionallyBridgeFromObjectiveC(NSDate?) -> Date (__hidden#3516_:261)
```

My assumption is publishedAtDate in swift code has type Date, not Date? or Date!. That's why I can't safety unwrap this property. And when SDK sends me nil code crashes.

**Comment by dbart01** [comment]
The issue seems to be that the `NSDateFormatter` cannot parse the date string because the format provided by the server doesn't match the one on the client. It therefore returns `nil` and crashed Swift-side when it's implicitly unwrapped. If that's the case, the solution would be for the server to provide consistent date formats. Do you have an example of the JSON response for the server that breaks using the current implementation?
