### ISSUE TITLE
Missing Field Error in checkout

### ISSUE THREAD

**Issue by SrmNarola** [Shopify/mobile-buy-sdk-ios#787]
I added product in cart using SDK. while creating checkout, I am getting this error:

```
Error Domain=BUYShopifyErrorDomain Code=412 "(null)" UserInfo={errors={
    "version_date" =     (
                {
            code = blank;
            message = "can't be blank";
            options =             {
            };
        }
    );
}}
```
```
**Request Parameter:**
{
checkout = {
"line_items" = (
{
grams = 28;
price = "100.00";
quantity = 5;
"requires_shipping" = 1;
title = "Default Title";
"variant_id" = 42031370186;
}
);
"marketing_attribution" = {
medium = iOS;
source = ZOX;
};
"source_name" = "mobile_app";
};
}
```
Would you please help me to solve out my issue where i am missing version_date field?

**Comment by dbart01** [comment]
The `v2.x` of Mobile Buy SDK is deprecated. We encourage everyone to migrate to `v3.x` - the latest GraphQL-based SDK instead. It also includes a comprehensive sample application that implements most common use cases for building custom storefronts on iOS.

If this is not something you're able to at the moment, adding `version_date` field to the `BUYCheckout` object shouldn't be too difficult.

**Comment by SrmNarola** [comment]
Is there any sample application or code in objective-C language with v3.x? I am integrating SDK in objective-C using this: [here](https://help.shopify.com/api/sdks/custom-storefront/mobile-buy-sdk/ios/integration-guide/checkout#building-a-cart)

**Comment by dbart01** [comment]
There's no sample code in Objective-C. Even though the SDK cannot be used in Objective-C directly, it is still possible to use it in your Objective-C app. You'll need to write a small bridging layer between Swift and Objective-C so that network operations are in done in Swift and the results are passed to the ViewModel layer in Objective-C.

**Comment by SrmNarola** [comment]
Thanks for helping.

**Comment by SrmNarola** [comment]
I have integrated Latest version of SDK and also created bridging file. I want to access graph.client.swift file into objective-C file as In main file Graph.swift , structure is used. I am not getting option of this file in Objective-C file. We only use those file who inherited from NSOBject.

Is there any other way to use this kind of files in Objective-C file?

**Comment by dbart01** [comment]
You can't use `Graph.Client` in Objective-C directly. You'll have to wrap it in your own `NSObject`-inheriting "Client" object.

**Comment by CYXie0402** [comment]
@SrmNarola  I had the same problem. How did you solve it？

**Comment by jvincent94** [comment]
> The `v2.x` of Mobile Buy SDK is deprecated. We encourage everyone to migrate to `v3.x` - the latest GraphQL-based SDK instead. It also includes a comprehensive sample application that implements most common use cases for building custom storefronts on iOS.
> 
> If this is not something you're able to at the moment, adding `version_date` field to the `BUYCheckout` object shouldn't be too difficult.

Hi @dbart01 I am maintaining an android app that uses SDK v2.1.0 and I bumped into this same problem. I tried to create a field for version_date inside Checkout.class and still I received this error
 `{"errors":{"version_date":[{"code":"blank","message":"can't be blank","options":{}}]}}`

Can you please help me about this issue? I'm stuck in here and I can't get a checkout token because of this issue. Hoping for your soonest response. Cheers
