### ISSUE TITLE
Unable to complete checkout with gift card (both Apple Pay and credit card): "Amount The amount of the payment must match the total of [totalPrice]"

### ISSUE THREAD

**Issue by jenchuah** [Shopify/mobile-buy-sdk-ios#927]
When I add a gift card to checkout and attempt to pay with credit card or Apple Pay, I get the response 
`["checkoutCompleteWithTokenizedPayment": {
    payment = "<null>";
    userErrors =     (
                {
            field =             (
                payment,
                amount
            );
            message = "Amount The amount of the payment must match the total of 124.00.";
        }
    );
}])`

In the example response above, 124.00 is the total price but since a gift card with a balance of 100.00 was applied, the amount due is 24.00. 

The amount of payment should not be the total price but the amount due.

I've tested this in my own app as well as Sample App version 3.1.9.

Would be great to have this resolved as my client uses gift cards quite a fair bit.

**Comment by dbart01** [comment]
The amount due isn't reduced by gift card applications. 

I think the order of operations is what's making it less clear. A gift card is actually charged on checkout completion, which means that `amountDue` is still $124.00. The API is designed so that you have to perform minimal arithmetic to use correctly. In this case, if you let the API do all the work and pass $124.00 in `amountDue`, everything should work as expected - the gift card will be drained and the credit card would receive a charge of $24.00.

**Comment by jenchuah** [comment]
The `paymentDue` IS reduced by gift card applications, see Mobile Buy SDK's Checkout class:
```
/// The amount left to be paid. This is equal to the cost of the line items, 
        /// taxes and shipping minus discounts and gift cards. 
        open var paymentDue: Decimal { get }
```
So when you add `paymentDue` to `[PKPaymentSummaryItem]` you will get the error "Amount The amount of the payment must match the total of [totalPrice] because as you said the API is expecting the total since the gift card isn't charged until checkout completion.
