### ISSUE TITLE
Error appearing on webURL checkout as cart has been modified and the shipping rate you previously selected no longer applies.

### ISSUE THREAD

**Issue by rohitkowadkar** [Shopify/mobile-buy-sdk-ios#979]
Getting following error 

I am proceeding checkout using Shopify Buy Sdk. 
I have created checkout object and updated using shipping address, applicable shipping rate also customer email. using all required mutations on checkout object.
Also when I am proceeding using WebUrl from the checkout object in WKwebview or SafariViewController it displays above error from the screenshot.

![IMG_A84A4DC8DAC8-1](https://user-images.githubusercontent.com/11057392/54993152-3531b300-4fe7-11e9-8b76-21b393580599.jpeg)

I have weight based shipping methods setup for all regions.

Same thing I checked using Android Buy Sdk it is working properly without giving any error.

**Comment by jamiemtdwyer** [comment]
Hi @rohitkowadkar,

Are you able to share the checkout token of the affected checkout?

It's possible that this is not a bug – if the contents of the checkout have truly changed (i.e. due to a script running at checkout) or the shipping address of the checkout has changed, the shipping rate has indeed become invalidated and you will need to select a new rate.

Happy to dig in given more information.

**Comment by rohitkowadkar** [comment]
Hi @jamiemtdwyer ,
thanks for replying.
here is the one of the checkout token for which I am getting error.
7b615306ea5ad4c113cb15defdd0d2ae

thank you in Advance

**Comment by rebeccajfriedman** [comment]
Hi @rohitkowadkar ! Are you still experiencing this issue? Please let us know (and provide a more recent token) and we can look into it.

**Comment by rohitkowadkar** [comment]
@rebeccajfriedman after updating to latest release of buy sdk this issue is not appearing! thanks for looking.
